vcs flow integration
Lightelligence/rules_verilog-legacy pull request #13
Opened 2021-08-12 03:32 UTC by justin371

vcs flow integration, the local sims passed.

2021-08-12 13:27 UTC, wstucker commented
@justin371 This changeset has VCS working only within the context of running simmer DV tests. All the unit tests and lint are not currently supported. Can we either please add support or add a disclaimer in the top-level documentation?

2021-08-12 13:27 UTC, wstucker requested changes

2021-08-12 13:27 UTC, wstucker commented on simulator.bzl
>  DPI_HEADERS = ["svdpi.h", "svdpi_compatibility.h"]
Can you please rename the existing `DPI_HEADERS` to `XRUN_DPI_HEADERS` for symmetry?

2021-08-12 13:27 UTC, wstucker commented on verilog/private/rtl.bzl
> +                flist_content.append("+incdir+{}".format(d))
Can you please add inline comments as to why this is necessary in VCS? Which tool is breaking without this incdir which should not be necessary?

2021-08-12 13:27 UTC, wstucker commented on verilog/private/dv.bzl
> +    #all_files = depset(trans_srcs.to_list() + trans_flists.to_list())
Please remove.

2021-08-12 13:27 UTC, wstucker commented on verilog/private/dv.bzl
> +            ##"{RUNTIME_ARGS}": ctx.expand_location("\n".join(ctx.attr.extra_runtime_args), targets = ctx.attr.extra_runfiles),
I think we should find a more graceful solution to this. While the arguments passed here obviously will not be compatible between xrun and vcs, just dropping them for VCS probably is not a good idea. It will be difficult to debug when someone actually uses it. Perhaps we need to make symmetric arguments.

2022-08-01 08:17 UTC, justin371 commented on simulator.bzl
>  DPI_HEADERS = ["svdpi.h", "svdpi_compatibility.h"]
renamed

2022-08-01 08:19 UTC, justin371 commented on verilog/private/rtl.bzl
> +                flist_content.append("+incdir+{}".format(d))
add the comment inline

2022-08-01 08:19 UTC, justin371 commented on verilog/private/dv.bzl
> +    #all_files = depset(trans_srcs.to_list() + trans_flists.to_list())
sure

2022-08-01 08:25 UTC, justin371 commented on verilog/private/dv.bzl
> +            ##"{RUNTIME_ARGS}": ctx.expand_location("\n".join(ctx.attr.extra_runtime_args), targets = ctx.attr.extra_runfiles),
yes.
so, let me do it later.

2022-08-01 08:27 UTC, closed without merging

2022-08-01 08:28 UTC, justin371 commented
No more needed now