Integrate the VCS flow
Lightelligence/rules_verilog-legacy pull request #29
Opened 2022-08-04 05:59 UTC by justin371

Integrate the VCS flow based on the latest commit number

2022-08-08 20:01 UTC, ciglass requested changes
Do we need to duplicate so many variables in rtl.bzl, dv.bzl, and verilog.bzl? For example, in verilog_rtl_library, instead of having a single flist output, there is now an flist_xrun and an flist_vcs. Is there a good way to structure this so that the specific simulator is abstract?

I'm concerned about code bloat - without a good abstraction level, the more simulators we support the more unique variables and outputs we'll have.

2022-08-08 20:01 UTC, ciglass commented on docs/defs.md
> -| default_sim_opts |  Default simulator options to pass to the simulator.   | <a href="https://bazel.build/docs/build-ref.html#labels">Label</a> | optional | @rules_verilog//vendors/cadence:verilog_d
Please do not modify defs.md directly. You should run //docs:defs_docs, then copy the built .md out of bazel-bin and into docs/defs.md. This is a manual process right now, unfortunately.

2022-08-10 17:41 UTC, ciglass commented
I read through the simmer code and these rules_verilog changes again, and I think it should be straightforward to merge the flists in the rule implementations. The per-vendor templates you've made are good, but I think we should instead use a new argument on verilog_dv_library and verilog_dv_tb that determines if we render from Synopsys or Cadence vendor templates. If we only render a single set of templates (instead of one per vendor) then the simmer code is simpler as well.

2022-08-11 01:29 UTC, justin371 commented on docs/defs.md
> -| default_sim_opts |  Default simulator options to pass to the simulator.   | <a href="https://bazel.build/docs/build-ref.html#labels">Label</a> | optional | @rules_verilog//vendors/cadence:verilog_d
thanks, will do it next time.

2022-08-11 01:37 UTC, justin371 commented
> 

2 groups of filelists is more clear for the different simulators, and maybe more efficient for the maintainance, will not be impact on other filelist, only more filelists are created in the bazel-bin path.

2022-08-11 01:44 UTC, justin371 commented
> 

Currently only 2 simulators are enough for us, and more filelists are created only.
Furthermore, The compilation and simulation results are different between the VCS and Xcelium, so the plan is to run both VCS and Xcelium in CN side.

2022-08-11 02:29 UTC, justin371 commented
one more words, it seems the "-makelib/-reflib" is a better approch:
![image](https://user-images.githubusercontent.com/35483333/184055102-cd6bc688-31c2-40ce-93d2-7ef3265c2290.png)

2022-08-16 02:02 UTC, merged