VCS flow integration
Lightelligence/rules_verilog-legacy pull request #31
Opened 2022-08-16 02:09 UTC by justin371

the VCS flow for the vcs and verdi in the project.

2022-08-23 00:56 UTC, ciglass commented
I opened #32 for future work on streamlining the per-tool implementations.

2022-08-23 01:54 UTC, ciglass requested changes

2022-08-23 01:54 UTC, ciglass commented on verilog/private/rtl.bzl
> +    flist_content_vcs = create_flist_content(ctx, gumi_path = gumi_path, allow_library_discovery = False)
Do we need to set `allow_library_discovery` to `False` for vcs? Or did you only use `False` as a way to distinguish between vcs and xrun in `create_flist_content`?

2022-08-23 01:54 UTC, ciglass commented on verilog/private/dv.bzl
> -        "_compile_args_template": attr.label(
Can you use a single `_compile_args_template` and `runtime_args_template` instead of splitting them? When I added support for Ascent Lint, I look at the `run_template` as a if/else control point in the lint implementation. I think it keeps the code much more concise. If we prevent the duplication of the flist code, then adding VCS support would require far fewer changes to `verilog/private`

2022-08-26 08:33 UTC, justin371 commented on verilog/private/rtl.bzl
> +    flist_content_vcs = create_flist_content(ctx, gumi_path = gumi_path, allow_library_discovery = False)
Yes, the +incdir is neccesarry for  VCS compilation

2022-09-15 15:17 UTC, ciglass approved these changes
These changes look good to me. I think this structure of duplicating the flists will work. As a future project, I'd like to see if we can make the Xcelium and VCS flists be identical. It would be less code to support in rules_verilog and in simmer.

2022-09-15 15:18 UTC, merged