simmer updates for xrun fsdb
Lightelligence/rules_verilog-legacy pull request #39
Opened 2022-11-03 22:21 UTC by jmlemay99

2022-11-03 22:31 UTC, ciglass requested changes, later dismissed

2022-11-03 22:31 UTC, ciglass commented on bin/simmer.py
> -shopt -s expand_aliases
Why did you remove this `shopt -s expand_aliases` and all the `source env.sh` calls? Are those related?

2022-11-04 14:04 UTC, guoqilu commented on bin/simmer.py
> -shopt -s expand_aliases
Hi @ciglass  just came across this. 
not trying to argue if this should be in this PR or not, just general thoughts over the rerun script:

- I'm holding the point we should take `env.sh` out of simmer related script completely because 
  - the path is a LT repo path
  - it is unnecessarily sourcing env.sh every time run simmer and repeated appending env vars like `PATH` (at one point, I looked at my `$PATH`, it becomes a huge list and hard to exam)
- I also think we should remove the `cd $PROJ_DIR` part along with `source env/env.sh` from rerun.sh:
  - this script is useless right now because the `cd $PROJ_DIR`part is defeating a most common case we need this script: handy way of re-producing a simulation from one repo to a different repo
  - with `cd $PROJ_DIR` will not hurt if someone is trying to rerun within same repo

2022-11-04 15:04 UTC, ciglass commented on bin/simmer.py
> -shopt -s expand_aliases
Those are good points about `env.sh` and `$PROJ_DIR`. It looks like the only usage either of those in @jmlemay99 's code anymore are in the SIM_TEMPLATE, which exports and uses `$PROJ_DIR` and the RERUN_TEMPLATE, which exports `$PROJ_DIR` and `cd`'s to it. I think the SIM_TEMPLATE is fine because the script rendered by the SIM_TEMPLATE is only used in a Subprocess call, which means the state doesn't bleed out to the shell that called simmer. I think we can remove the `cd` from the RERUN template, but I think it still needs the `export` because simmer relies on the `$PROJ_DIR` environment variable to be set.

I think my original question is unanswered though - what does the `shopt -s expand_aliases` do? I thought we needed that to handle the fact that at LT we internally `alias` simmer and we need all our shells to recognize the alias.

2022-11-04 15:12 UTC, guoqilu commented on bin/simmer.py
> -shopt -s expand_aliases
I'm fine with leaving the shop -s expand_aliases, that's extension support of alias, there is no harm leave it in.

an side note though, we should avoid using `alias` overall, as `lsf` doesn't support `alias` and `lsl` is mandatory due to CN site IT env.
we don't need `lsf` here, but we should be prepared when our team expands and when there is need of `lsf` to manage resource for regression runs.

2022-11-04 15:17 UTC, guoqilu commented on bin/simmer.py
> -shopt -s expand_aliases
and the $PROJ_DIR, 
I'm fine with the env var export for `sim.sh`, just the `cd` part

2022-11-04 16:15 UTC, jmlemay99 commented on bin/simmer.py
> -shopt -s expand_aliases
i removed the PROJ_DIR defintion from the rerun_template in my latest commit.

2022-11-04 16:50 UTC, guoqilu commented on bin/simmer.py
> -cd $PROJ_DIR
Do you mind remove the export part as well so that people can use this script to rerun a test from different repo/ci and replicate in local PROJ_DIR

2022-11-04 17:03 UTC, jmlemay99 commented on bin/simmer.py
> -cd $PROJ_DIR
Done.

2022-11-04 18:13 UTC, ciglass approved these changes

2022-11-04 18:24 UTC, merged