simmer libs and executables
Lightelligence/rules_verilog-legacy pull request #42
Opened 2022-11-17 19:16 UTC by jmlemay99

2022-11-18 18:14 UTC, guoqilu approved these changes

2022-11-18 21:10 UTC, ciglass requested changes

2022-11-18 21:10 UTC, ciglass commented on bin/simmer.py
> -# Bigger libraries (better to place these later for dependency ordering
Minor nit - I like to these boilerplate comments like these unchanged, even if it's not 100% accurate to this script. It makes it easier to grep for it, or to copy it out and make a new script.

2022-11-18 21:10 UTC, ciglass commented on bin/simmer.py
> -{% if options.simulator == 'xrun' -%}call {% endif -%}fsdbAll on
Were these FSDB changes intentional?

2022-11-18 21:10 UTC, ciglass commented on bin/simmer.py
> -cd $PROJ_DIR
I thought you removed most of these $PROJ_DIR and env.sh changes in a different PR. Why are they showing up again?

2022-11-18 21:10 UTC, ciglass commented on bin/simmer.py
> +        super(VCompJob, self).__init__(rcfg, name, options.timeout)
Was timeout not being propagated before? Was that a functional bug in simmer?

2022-11-18 21:10 UTC, ciglass commented on lib/job_runner.py
> +#!/usr/bin/env python
Minor nit - does it make sense to call this file job_runner? It has classes to run jobs, but also has a few other job-related functions

2022-11-18 21:10 UTC, ciglass commented on lib/job_runner.py
> +"""JobStatus class definition."""
I think this file should have a different docstring and the docstring you have should be inside the JobStatus class.

Relatedly, shouldn't yapf (or one of our other CI tests) have caught the fact that we're missing many docstrings in here?

2022-11-18 21:10 UTC, ciglass commented on lib/regression.py
> +"""Regression config objec definition."""
I have the same comments about docstrings here as I did in the job_runner.py file

2022-11-18 21:10 UTC, ciglass commented on lib/rv_utils.py
> +class IterationCfg():
Is there a better home for this? Is this more closely related to a job or a regression? Or is it here because it's tied to neither specifically?

2022-11-18 21:10 UTC, ciglass commented on lib/rv_utils.py
> +def print_summary(rcfg, vcomp_jobs, icfgs, jm):
Same question as above - does it make sense to keep this here, or more tied to Jobs?

2022-11-21 16:00 UTC, jmlemay99 commented on lib/job_runner.py
> +#!/usr/bin/env python
I'm open to more intuitive suggestions.  The module began with just the job-running class definitions, then expanded (as you pointed out) to other job-related functions.  How do you feel about "jobs.py" or "job_lib.py"?

2022-11-21 16:10 UTC, jmlemay99 commented on bin/simmer.py
> +        super(VCompJob, self).__init__(rcfg, name, options.timeout)
The options object is scoped in the main namespace, but the Job class definition now lives in a different namespace.  So the timeout value needs to be passed as an argument to Job's __init__( ) function.

I'm not sure if Python allows for something like "main.options.timeout" outside of the main namespace, but I don't want to create that dependency on the executable.

2022-11-21 16:31 UTC, jmlemay99 commented on bin/simmer.py
> -{% if options.simulator == 'xrun' -%}call {% endif -%}fsdbAll on
There's no change here as part of this PR.  If you're seeing a diff from Github, I may have forgotten to merge with master.

2022-11-21 16:47 UTC, jmlemay99 commented on bin/simmer.py
> -cd $PROJ_DIR
Removed.

2022-11-21 16:47 UTC, jmlemay99 commented on bin/simmer.py
> -# Bigger libraries (better to place these later for dependency ordering
Reverted.

2022-11-21 17:51 UTC, jmlemay99 commented on lib/rv_utils.py
> +class IterationCfg():
in my mind, the RV utils module was for class definitions that weren't tied to anything specifically.

2022-11-21 17:52 UTC, jmlemay99 commented on lib/rv_utils.py
> +def print_summary(rcfg, vcomp_jobs, icfgs, jm):
It's a message printing function, so in my mind, it feel more into a "miscellaneous" category, rather than a "Job" category.

2022-11-21 18:05 UTC, jmlemay99 commented on lib/job_runner.py
> +"""JobStatus class definition."""
yapf is new to me.  there's nothing in the rules_verilog style definition that requires a docstring for every module and class.  does yapf default behavior require it?  yapf is implemented in python....  how do we know what version of yapf is being used by GitHub CI?

2022-11-21 18:17 UTC, jmlemay99 commented on lib/regression.py
> +"""Regression config objec definition."""
I removed this docstring.

2022-11-21 20:16 UTC, ciglass commented on bin/simmer.py
> +        super(VCompJob, self).__init__(rcfg, name, options.timeout)
Hmm, the fact that `options` was in the namespace before seems like a bug to me.

Instead of passing in options.timeout, could you make `Job.__init__` use `rcfg.options.timeout` directly and remove the argument from the `__init__`? As far as I can tell, `options` is already a field of `RegressionConfig` so we shouldn't need to pass it through again.

2022-11-21 20:16 UTC, ciglass commented on lib/job_runner.py
> +#!/usr/bin/env python
I like `job_lib`

2022-11-21 20:19 UTC, ciglass commented on lib/job_runner.py
> +"""JobStatus class definition."""
Now that I think more about this, I think the problem is that we're running yapf but not pylint. yapf is a formatter rather than a linter. I think a linter (like pylint) would have caught this.

I'll open a separate issue to enable pylint on CI in github, then mark this issue as resolved.

2022-11-21 20:30 UTC, ciglass commented on lib/job_runner.py
> +"""JobStatus class definition."""
https://github.com/Lightelligence/rules_verilog/issues/43

2022-11-21 20:48 UTC, ciglass approved these changes

2022-11-21 21:06 UTC, merged